services:
  - type: web
    name: nhieu-ra-it-bi-online
    env: node
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
